name: ci
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install overrides
      - run: pip install mkdocs-material
      - run: pip install python-frontmatter
      - run: pip install mkdocs-glightbox
      - run: pip3 install mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-macros-plugin
      - run: pip3 install mkdocs-git-authors-plugin
      - run: pip3 install mkdocs-exclude
      - run: pip install mkdocs-awesome-pages-plugin
      - run: pip install mkdocs-obsidian-support-plugin
      - run: mkdocs gh-deploy --force